services:

  flink-dev:
    container_name: flink
    image: hibuz/flink-dev:simple
    ports:
      - 9870:9870
      - 8088:8088
      - 19888:19888
      - 16010:16010
      - 4040:4040
      - 8090:8090
      - 8091:8091
      - 18080:18080
      - 10002:10002
      - 8081:8081
    command: #hive,spark,hbase,yarn,historyserver
    volumes:
      - flink-vol:/tmp
      - ..:/home/hadoop/flink-example:cached

volumes:
  flink-vol: {}